services:
  db:
    image: postgis/postgis:15-3.4
    platform: linux/amd64
    environment:
      POSTGRES_USER: gis_user
      POSTGRES_PASSWORD: gis_pass
      POSTGRES_DB: nyc_bis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: